FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bookworm

RUN install_packages \
    libcamera-dev \
    libcamera-apps-lite \
    v4l-utils

WORKDIR /usr/src/app

COPY start.sh ./

RUN chmod +x start.sh

# RUN usermod -a -G video root

ENV UDEV=on

CMD ["sh","./start.sh"]
