version: "2.1"

services:
  libcamera:
    build: ./
    restart: always
    privileged: true
    # labels:
    #   io.balena.features.kernel-modules: '1'
    #   io.balena.features.firmware: '1'
    # group_add:
    #   - video

